// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal.Persistence.Database;

namespace Personal.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Personal")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Personal.Domain.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Usuario_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Usuario_Id")
                        .IsUnique()
                        .HasFilter("[Usuario_Id] IS NOT NULL");

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Apellidos 1",
                            Dni = "76368626",
                            Nombres = "Nombres 1",
                            Usuario_Id = "1"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Apellidos 2",
                            Dni = "76368627",
                            Nombres = "Nombres 2",
                            Usuario_Id = "2"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Apellidos 3",
                            Dni = "76368628",
                            Nombres = "Nombres 3",
                            Usuario_Id = "3"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "Apellidos 4",
                            Dni = "76368629",
                            Nombres = "Nombres 4",
                            Usuario_Id = "4"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "Apellidos 5",
                            Dni = "76368630",
                            Nombres = "Nombres 5",
                            Usuario_Id = "5"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellidos = "Apellidos 6",
                            Dni = "76368631",
                            Nombres = "Nombres 6",
                            Usuario_Id = "6"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellidos = "Apellidos 7",
                            Dni = "76368632",
                            Nombres = "Nombres 7",
                            Usuario_Id = "7"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellidos = "Apellidos 8",
                            Dni = "76368633",
                            Nombres = "Nombres 8",
                            Usuario_Id = "8"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Apellidos = "Apellidos 9",
                            Dni = "76368634",
                            Nombres = "Nombres 9",
                            Usuario_Id = "9"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellidos = "Apellidos 10",
                            Dni = "76368635",
                            Nombres = "Nombres 10",
                            Usuario_Id = "10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
