// <auto-generated />
using System;
using Clientes.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clientes.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211203133140_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Clientes")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Clientes.Domain.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("Usuario_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Usuario_Id")
                        .IsUnique()
                        .HasFilter("[Usuario_Id] IS NOT NULL");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Apellido 1",
                            Celular = "942024657",
                            Dni = "76368636",
                            Email = "paciente1@gmail.com",
                            FechaNacimiento = new DateTime(2003, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 1",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "11"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Apellido 2",
                            Celular = "942024658",
                            Dni = "76368637",
                            Email = "paciente2@gmail.com",
                            FechaNacimiento = new DateTime(2002, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 2",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "12"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Apellido 3",
                            Celular = "942024659",
                            Dni = "76368638",
                            Email = "paciente3@gmail.com",
                            FechaNacimiento = new DateTime(2001, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 3",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "13"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "Apellido 4",
                            Celular = "942024660",
                            Dni = "76368639",
                            Email = "paciente4@gmail.com",
                            FechaNacimiento = new DateTime(2000, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 4",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "14"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "Apellido 5",
                            Celular = "942024661",
                            Dni = "76368640",
                            Email = "paciente5@gmail.com",
                            FechaNacimiento = new DateTime(1999, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 5",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "15"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellidos = "Apellido 6",
                            Celular = "942024662",
                            Dni = "76368641",
                            Email = "paciente6@gmail.com",
                            FechaNacimiento = new DateTime(1998, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 6",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "16"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellidos = "Apellido 7",
                            Celular = "942024663",
                            Dni = "76368642",
                            Email = "paciente7@gmail.com",
                            FechaNacimiento = new DateTime(1997, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 7",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "17"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellidos = "Apellido 8",
                            Celular = "942024664",
                            Dni = "76368643",
                            Email = "paciente8@gmail.com",
                            FechaNacimiento = new DateTime(1996, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 8",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "18"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Apellidos = "Apellido 9",
                            Celular = "942024665",
                            Dni = "76368644",
                            Email = "paciente9@gmail.com",
                            FechaNacimiento = new DateTime(1995, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 9",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "19"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellidos = "Apellido 10",
                            Celular = "942024666",
                            Dni = "76368645",
                            Email = "paciente10@gmail.com",
                            FechaNacimiento = new DateTime(1994, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 10",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "20"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Apellidos = "Apellido 11",
                            Celular = "942024667",
                            Dni = "76368646",
                            Email = "paciente11@gmail.com",
                            FechaNacimiento = new DateTime(1993, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 11",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "21"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Apellidos = "Apellido 12",
                            Celular = "942024668",
                            Dni = "76368647",
                            Email = "paciente12@gmail.com",
                            FechaNacimiento = new DateTime(1992, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 12",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "22"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Apellidos = "Apellido 13",
                            Celular = "942024669",
                            Dni = "76368648",
                            Email = "paciente13@gmail.com",
                            FechaNacimiento = new DateTime(1991, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 13",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "23"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Apellidos = "Apellido 14",
                            Celular = "942024670",
                            Dni = "76368649",
                            Email = "paciente14@gmail.com",
                            FechaNacimiento = new DateTime(1990, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 14",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "24"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Apellidos = "Apellido 15",
                            Celular = "942024671",
                            Dni = "76368650",
                            Email = "paciente15@gmail.com",
                            FechaNacimiento = new DateTime(1989, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 15",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "25"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Apellidos = "Apellido 16",
                            Celular = "942024672",
                            Dni = "76368651",
                            Email = "paciente16@gmail.com",
                            FechaNacimiento = new DateTime(1988, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 16",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "26"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Apellidos = "Apellido 17",
                            Celular = "942024673",
                            Dni = "76368652",
                            Email = "paciente17@gmail.com",
                            FechaNacimiento = new DateTime(1987, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 17",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "27"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Apellidos = "Apellido 18",
                            Celular = "942024674",
                            Dni = "76368653",
                            Email = "paciente18@gmail.com",
                            FechaNacimiento = new DateTime(1986, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 18",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "28"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Apellidos = "Apellido 19",
                            Celular = "942024675",
                            Dni = "76368654",
                            Email = "paciente19@gmail.com",
                            FechaNacimiento = new DateTime(1985, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 19",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "29"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Apellidos = "Apellido 20",
                            Celular = "942024676",
                            Dni = "76368655",
                            Email = "paciente20@gmail.com",
                            FechaNacimiento = new DateTime(1984, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 20",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "30"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Apellidos = "Apellido 21",
                            Celular = "942024677",
                            Dni = "76368656",
                            Email = "paciente21@gmail.com",
                            FechaNacimiento = new DateTime(1983, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 21",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "31"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Apellidos = "Apellido 22",
                            Celular = "942024678",
                            Dni = "76368657",
                            Email = "paciente22@gmail.com",
                            FechaNacimiento = new DateTime(1982, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 22",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "32"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Apellidos = "Apellido 23",
                            Celular = "942024679",
                            Dni = "76368658",
                            Email = "paciente23@gmail.com",
                            FechaNacimiento = new DateTime(1981, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 23",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "33"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Apellidos = "Apellido 24",
                            Celular = "942024680",
                            Dni = "76368659",
                            Email = "paciente24@gmail.com",
                            FechaNacimiento = new DateTime(1980, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 24",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "34"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Apellidos = "Apellido 25",
                            Celular = "942024681",
                            Dni = "76368660",
                            Email = "paciente25@gmail.com",
                            FechaNacimiento = new DateTime(1979, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 25",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "35"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Apellidos = "Apellido 26",
                            Celular = "942024682",
                            Dni = "76368661",
                            Email = "paciente26@gmail.com",
                            FechaNacimiento = new DateTime(1978, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 26",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "36"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            Apellidos = "Apellido 27",
                            Celular = "942024683",
                            Dni = "76368662",
                            Email = "paciente27@gmail.com",
                            FechaNacimiento = new DateTime(1977, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 27",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "37"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            Apellidos = "Apellido 28",
                            Celular = "942024684",
                            Dni = "76368663",
                            Email = "paciente28@gmail.com",
                            FechaNacimiento = new DateTime(1976, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 28",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "38"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            Apellidos = "Apellido 29",
                            Celular = "942024685",
                            Dni = "76368664",
                            Email = "paciente29@gmail.com",
                            FechaNacimiento = new DateTime(1975, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 29",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "39"
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            Apellidos = "Apellido 30",
                            Celular = "942024686",
                            Dni = "76368665",
                            Email = "paciente30@gmail.com",
                            FechaNacimiento = new DateTime(1974, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 30",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "40"
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            Apellidos = "Apellido 31",
                            Celular = "942024687",
                            Dni = "76368666",
                            Email = "paciente31@gmail.com",
                            FechaNacimiento = new DateTime(1973, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 31",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "41"
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            Apellidos = "Apellido 32",
                            Celular = "942024688",
                            Dni = "76368667",
                            Email = "paciente32@gmail.com",
                            FechaNacimiento = new DateTime(1972, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 32",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "42"
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            Apellidos = "Apellido 33",
                            Celular = "942024689",
                            Dni = "76368668",
                            Email = "paciente33@gmail.com",
                            FechaNacimiento = new DateTime(1971, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 33",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "43"
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            Apellidos = "Apellido 34",
                            Celular = "942024690",
                            Dni = "76368669",
                            Email = "paciente34@gmail.com",
                            FechaNacimiento = new DateTime(1970, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 34",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "44"
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            Apellidos = "Apellido 35",
                            Celular = "942024691",
                            Dni = "76368670",
                            Email = "paciente35@gmail.com",
                            FechaNacimiento = new DateTime(1969, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 35",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "45"
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            Apellidos = "Apellido 36",
                            Celular = "942024692",
                            Dni = "76368671",
                            Email = "paciente36@gmail.com",
                            FechaNacimiento = new DateTime(1968, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 36",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "46"
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            Apellidos = "Apellido 37",
                            Celular = "942024693",
                            Dni = "76368672",
                            Email = "paciente37@gmail.com",
                            FechaNacimiento = new DateTime(1967, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 37",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "47"
                        },
                        new
                        {
                            Id = 38,
                            Activo = true,
                            Apellidos = "Apellido 38",
                            Celular = "942024694",
                            Dni = "76368673",
                            Email = "paciente38@gmail.com",
                            FechaNacimiento = new DateTime(1966, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 38",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "48"
                        },
                        new
                        {
                            Id = 39,
                            Activo = true,
                            Apellidos = "Apellido 39",
                            Celular = "942024695",
                            Dni = "76368674",
                            Email = "paciente39@gmail.com",
                            FechaNacimiento = new DateTime(1965, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 39",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "49"
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            Apellidos = "Apellido 40",
                            Celular = "942024696",
                            Dni = "76368675",
                            Email = "paciente40@gmail.com",
                            FechaNacimiento = new DateTime(1964, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 40",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "50"
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            Apellidos = "Apellido 41",
                            Celular = "942024697",
                            Dni = "76368676",
                            Email = "paciente41@gmail.com",
                            FechaNacimiento = new DateTime(1963, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 41",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "51"
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            Apellidos = "Apellido 42",
                            Celular = "942024698",
                            Dni = "76368677",
                            Email = "paciente42@gmail.com",
                            FechaNacimiento = new DateTime(1962, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 42",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "52"
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            Apellidos = "Apellido 43",
                            Celular = "942024699",
                            Dni = "76368678",
                            Email = "paciente43@gmail.com",
                            FechaNacimiento = new DateTime(1961, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 43",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "53"
                        },
                        new
                        {
                            Id = 44,
                            Activo = true,
                            Apellidos = "Apellido 44",
                            Celular = "942024700",
                            Dni = "76368679",
                            Email = "paciente44@gmail.com",
                            FechaNacimiento = new DateTime(1960, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 44",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "54"
                        },
                        new
                        {
                            Id = 45,
                            Activo = true,
                            Apellidos = "Apellido 45",
                            Celular = "942024701",
                            Dni = "76368680",
                            Email = "paciente45@gmail.com",
                            FechaNacimiento = new DateTime(1959, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 45",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "55"
                        },
                        new
                        {
                            Id = 46,
                            Activo = true,
                            Apellidos = "Apellido 46",
                            Celular = "942024702",
                            Dni = "76368681",
                            Email = "paciente46@gmail.com",
                            FechaNacimiento = new DateTime(1958, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 46",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "56"
                        },
                        new
                        {
                            Id = 47,
                            Activo = true,
                            Apellidos = "Apellido 47",
                            Celular = "942024703",
                            Dni = "76368682",
                            Email = "paciente47@gmail.com",
                            FechaNacimiento = new DateTime(1957, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 47",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "57"
                        },
                        new
                        {
                            Id = 48,
                            Activo = true,
                            Apellidos = "Apellido 48",
                            Celular = "942024704",
                            Dni = "76368683",
                            Email = "paciente48@gmail.com",
                            FechaNacimiento = new DateTime(1956, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 48",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "58"
                        },
                        new
                        {
                            Id = 49,
                            Activo = true,
                            Apellidos = "Apellido 49",
                            Celular = "942024705",
                            Dni = "76368684",
                            Email = "paciente49@gmail.com",
                            FechaNacimiento = new DateTime(1955, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 49",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "59"
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            Apellidos = "Apellido 50",
                            Celular = "942024706",
                            Dni = "76368685",
                            Email = "paciente50@gmail.com",
                            FechaNacimiento = new DateTime(1954, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 50",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "60"
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            Apellidos = "Apellido 51",
                            Celular = "942024707",
                            Dni = "76368686",
                            Email = "paciente51@gmail.com",
                            FechaNacimiento = new DateTime(1953, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 51",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "61"
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            Apellidos = "Apellido 52",
                            Celular = "942024708",
                            Dni = "76368687",
                            Email = "paciente52@gmail.com",
                            FechaNacimiento = new DateTime(1952, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 52",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "62"
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            Apellidos = "Apellido 53",
                            Celular = "942024709",
                            Dni = "76368688",
                            Email = "paciente53@gmail.com",
                            FechaNacimiento = new DateTime(1951, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 53",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "63"
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            Apellidos = "Apellido 54",
                            Celular = "942024710",
                            Dni = "76368689",
                            Email = "paciente54@gmail.com",
                            FechaNacimiento = new DateTime(1950, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 54",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "64"
                        },
                        new
                        {
                            Id = 55,
                            Activo = true,
                            Apellidos = "Apellido 55",
                            Celular = "942024711",
                            Dni = "76368690",
                            Email = "paciente55@gmail.com",
                            FechaNacimiento = new DateTime(1949, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 55",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "65"
                        },
                        new
                        {
                            Id = 56,
                            Activo = true,
                            Apellidos = "Apellido 56",
                            Celular = "942024712",
                            Dni = "76368691",
                            Email = "paciente56@gmail.com",
                            FechaNacimiento = new DateTime(1948, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 56",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "66"
                        },
                        new
                        {
                            Id = 57,
                            Activo = true,
                            Apellidos = "Apellido 57",
                            Celular = "942024713",
                            Dni = "76368692",
                            Email = "paciente57@gmail.com",
                            FechaNacimiento = new DateTime(1947, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 57",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "67"
                        },
                        new
                        {
                            Id = 58,
                            Activo = true,
                            Apellidos = "Apellido 58",
                            Celular = "942024714",
                            Dni = "76368693",
                            Email = "paciente58@gmail.com",
                            FechaNacimiento = new DateTime(1946, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 58",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "68"
                        },
                        new
                        {
                            Id = 59,
                            Activo = true,
                            Apellidos = "Apellido 59",
                            Celular = "942024715",
                            Dni = "76368694",
                            Email = "paciente59@gmail.com",
                            FechaNacimiento = new DateTime(1945, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 59",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "69"
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            Apellidos = "Apellido 60",
                            Celular = "942024716",
                            Dni = "76368695",
                            Email = "paciente60@gmail.com",
                            FechaNacimiento = new DateTime(1944, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 60",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "70"
                        },
                        new
                        {
                            Id = 61,
                            Activo = true,
                            Apellidos = "Apellido 61",
                            Celular = "942024717",
                            Dni = "76368696",
                            Email = "paciente61@gmail.com",
                            FechaNacimiento = new DateTime(1943, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 61",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "71"
                        },
                        new
                        {
                            Id = 62,
                            Activo = true,
                            Apellidos = "Apellido 62",
                            Celular = "942024718",
                            Dni = "76368697",
                            Email = "paciente62@gmail.com",
                            FechaNacimiento = new DateTime(1942, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 62",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "72"
                        },
                        new
                        {
                            Id = 63,
                            Activo = true,
                            Apellidos = "Apellido 63",
                            Celular = "942024719",
                            Dni = "76368698",
                            Email = "paciente63@gmail.com",
                            FechaNacimiento = new DateTime(1941, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 63",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "73"
                        },
                        new
                        {
                            Id = 64,
                            Activo = true,
                            Apellidos = "Apellido 64",
                            Celular = "942024720",
                            Dni = "76368699",
                            Email = "paciente64@gmail.com",
                            FechaNacimiento = new DateTime(1940, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 64",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "74"
                        },
                        new
                        {
                            Id = 65,
                            Activo = true,
                            Apellidos = "Apellido 65",
                            Celular = "942024721",
                            Dni = "76368700",
                            Email = "paciente65@gmail.com",
                            FechaNacimiento = new DateTime(1939, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 65",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "75"
                        },
                        new
                        {
                            Id = 66,
                            Activo = true,
                            Apellidos = "Apellido 66",
                            Celular = "942024722",
                            Dni = "76368701",
                            Email = "paciente66@gmail.com",
                            FechaNacimiento = new DateTime(1938, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 66",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "76"
                        },
                        new
                        {
                            Id = 67,
                            Activo = true,
                            Apellidos = "Apellido 67",
                            Celular = "942024723",
                            Dni = "76368702",
                            Email = "paciente67@gmail.com",
                            FechaNacimiento = new DateTime(1937, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 67",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "77"
                        },
                        new
                        {
                            Id = 68,
                            Activo = true,
                            Apellidos = "Apellido 68",
                            Celular = "942024724",
                            Dni = "76368703",
                            Email = "paciente68@gmail.com",
                            FechaNacimiento = new DateTime(1936, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 68",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "78"
                        },
                        new
                        {
                            Id = 69,
                            Activo = true,
                            Apellidos = "Apellido 69",
                            Celular = "942024725",
                            Dni = "76368704",
                            Email = "paciente69@gmail.com",
                            FechaNacimiento = new DateTime(1935, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 69",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "79"
                        },
                        new
                        {
                            Id = 70,
                            Activo = true,
                            Apellidos = "Apellido 70",
                            Celular = "942024726",
                            Dni = "76368705",
                            Email = "paciente70@gmail.com",
                            FechaNacimiento = new DateTime(1934, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 70",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "80"
                        },
                        new
                        {
                            Id = 71,
                            Activo = true,
                            Apellidos = "Apellido 71",
                            Celular = "942024727",
                            Dni = "76368706",
                            Email = "paciente71@gmail.com",
                            FechaNacimiento = new DateTime(1933, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 71",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "81"
                        },
                        new
                        {
                            Id = 72,
                            Activo = true,
                            Apellidos = "Apellido 72",
                            Celular = "942024728",
                            Dni = "76368707",
                            Email = "paciente72@gmail.com",
                            FechaNacimiento = new DateTime(1932, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 72",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "82"
                        },
                        new
                        {
                            Id = 73,
                            Activo = true,
                            Apellidos = "Apellido 73",
                            Celular = "942024729",
                            Dni = "76368708",
                            Email = "paciente73@gmail.com",
                            FechaNacimiento = new DateTime(1931, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 73",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "83"
                        },
                        new
                        {
                            Id = 74,
                            Activo = true,
                            Apellidos = "Apellido 74",
                            Celular = "942024730",
                            Dni = "76368709",
                            Email = "paciente74@gmail.com",
                            FechaNacimiento = new DateTime(1930, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 74",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "84"
                        },
                        new
                        {
                            Id = 75,
                            Activo = true,
                            Apellidos = "Apellido 75",
                            Celular = "942024731",
                            Dni = "76368710",
                            Email = "paciente75@gmail.com",
                            FechaNacimiento = new DateTime(1929, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 75",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "85"
                        },
                        new
                        {
                            Id = 76,
                            Activo = true,
                            Apellidos = "Apellido 76",
                            Celular = "942024732",
                            Dni = "76368711",
                            Email = "paciente76@gmail.com",
                            FechaNacimiento = new DateTime(1928, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 76",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "86"
                        },
                        new
                        {
                            Id = 77,
                            Activo = true,
                            Apellidos = "Apellido 77",
                            Celular = "942024733",
                            Dni = "76368712",
                            Email = "paciente77@gmail.com",
                            FechaNacimiento = new DateTime(1927, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 77",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "87"
                        },
                        new
                        {
                            Id = 78,
                            Activo = true,
                            Apellidos = "Apellido 78",
                            Celular = "942024734",
                            Dni = "76368713",
                            Email = "paciente78@gmail.com",
                            FechaNacimiento = new DateTime(1926, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 78",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "88"
                        },
                        new
                        {
                            Id = 79,
                            Activo = true,
                            Apellidos = "Apellido 79",
                            Celular = "942024735",
                            Dni = "76368714",
                            Email = "paciente79@gmail.com",
                            FechaNacimiento = new DateTime(1925, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 79",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "89"
                        },
                        new
                        {
                            Id = 80,
                            Activo = true,
                            Apellidos = "Apellido 80",
                            Celular = "942024736",
                            Dni = "76368715",
                            Email = "paciente80@gmail.com",
                            FechaNacimiento = new DateTime(1924, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 80",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "90"
                        },
                        new
                        {
                            Id = 81,
                            Activo = true,
                            Apellidos = "Apellido 81",
                            Celular = "942024737",
                            Dni = "76368716",
                            Email = "paciente81@gmail.com",
                            FechaNacimiento = new DateTime(1923, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 81",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "91"
                        },
                        new
                        {
                            Id = 82,
                            Activo = true,
                            Apellidos = "Apellido 82",
                            Celular = "942024738",
                            Dni = "76368717",
                            Email = "paciente82@gmail.com",
                            FechaNacimiento = new DateTime(1922, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 82",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "92"
                        },
                        new
                        {
                            Id = 83,
                            Activo = true,
                            Apellidos = "Apellido 83",
                            Celular = "942024739",
                            Dni = "76368718",
                            Email = "paciente83@gmail.com",
                            FechaNacimiento = new DateTime(1921, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 83",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "93"
                        },
                        new
                        {
                            Id = 84,
                            Activo = true,
                            Apellidos = "Apellido 84",
                            Celular = "942024740",
                            Dni = "76368719",
                            Email = "paciente84@gmail.com",
                            FechaNacimiento = new DateTime(1920, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 84",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "94"
                        },
                        new
                        {
                            Id = 85,
                            Activo = true,
                            Apellidos = "Apellido 85",
                            Celular = "942024741",
                            Dni = "76368720",
                            Email = "paciente85@gmail.com",
                            FechaNacimiento = new DateTime(1919, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 85",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "95"
                        },
                        new
                        {
                            Id = 86,
                            Activo = true,
                            Apellidos = "Apellido 86",
                            Celular = "942024742",
                            Dni = "76368721",
                            Email = "paciente86@gmail.com",
                            FechaNacimiento = new DateTime(1918, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 86",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "96"
                        },
                        new
                        {
                            Id = 87,
                            Activo = true,
                            Apellidos = "Apellido 87",
                            Celular = "942024743",
                            Dni = "76368722",
                            Email = "paciente87@gmail.com",
                            FechaNacimiento = new DateTime(1917, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 87",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "97"
                        },
                        new
                        {
                            Id = 88,
                            Activo = true,
                            Apellidos = "Apellido 88",
                            Celular = "942024744",
                            Dni = "76368723",
                            Email = "paciente88@gmail.com",
                            FechaNacimiento = new DateTime(1916, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 88",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "98"
                        },
                        new
                        {
                            Id = 89,
                            Activo = true,
                            Apellidos = "Apellido 89",
                            Celular = "942024745",
                            Dni = "76368724",
                            Email = "paciente89@gmail.com",
                            FechaNacimiento = new DateTime(1915, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 89",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "99"
                        },
                        new
                        {
                            Id = 90,
                            Activo = true,
                            Apellidos = "Apellido 90",
                            Celular = "942024746",
                            Dni = "76368725",
                            Email = "paciente90@gmail.com",
                            FechaNacimiento = new DateTime(1914, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 90",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "100"
                        },
                        new
                        {
                            Id = 91,
                            Activo = true,
                            Apellidos = "Apellido 91",
                            Celular = "942024747",
                            Dni = "76368726",
                            Email = "paciente91@gmail.com",
                            FechaNacimiento = new DateTime(1913, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 91",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "101"
                        },
                        new
                        {
                            Id = 92,
                            Activo = true,
                            Apellidos = "Apellido 92",
                            Celular = "942024748",
                            Dni = "76368727",
                            Email = "paciente92@gmail.com",
                            FechaNacimiento = new DateTime(1912, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 92",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "102"
                        },
                        new
                        {
                            Id = 93,
                            Activo = true,
                            Apellidos = "Apellido 93",
                            Celular = "942024749",
                            Dni = "76368728",
                            Email = "paciente93@gmail.com",
                            FechaNacimiento = new DateTime(1911, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 93",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "103"
                        },
                        new
                        {
                            Id = 94,
                            Activo = true,
                            Apellidos = "Apellido 94",
                            Celular = "942024750",
                            Dni = "76368729",
                            Email = "paciente94@gmail.com",
                            FechaNacimiento = new DateTime(1910, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 94",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "104"
                        },
                        new
                        {
                            Id = 95,
                            Activo = true,
                            Apellidos = "Apellido 95",
                            Celular = "942024751",
                            Dni = "76368730",
                            Email = "paciente95@gmail.com",
                            FechaNacimiento = new DateTime(1909, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 95",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "105"
                        },
                        new
                        {
                            Id = 96,
                            Activo = true,
                            Apellidos = "Apellido 96",
                            Celular = "942024752",
                            Dni = "76368731",
                            Email = "paciente96@gmail.com",
                            FechaNacimiento = new DateTime(1908, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 96",
                            Region = "Puno",
                            Sexo = 0,
                            Usuario_Id = "106"
                        },
                        new
                        {
                            Id = 97,
                            Activo = true,
                            Apellidos = "Apellido 97",
                            Celular = "942024753",
                            Dni = "76368732",
                            Email = "paciente97@gmail.com",
                            FechaNacimiento = new DateTime(1907, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 97",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "107"
                        },
                        new
                        {
                            Id = 98,
                            Activo = true,
                            Apellidos = "Apellido 98",
                            Celular = "942024754",
                            Dni = "76368733",
                            Email = "paciente98@gmail.com",
                            FechaNacimiento = new DateTime(1906, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 98",
                            Region = "Tacna",
                            Sexo = 0,
                            Usuario_Id = "108"
                        },
                        new
                        {
                            Id = 99,
                            Activo = true,
                            Apellidos = "Apellido 99",
                            Celular = "942024755",
                            Dni = "76368734",
                            Email = "paciente99@gmail.com",
                            FechaNacimiento = new DateTime(1905, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 99",
                            Region = "Tacna",
                            Sexo = 1,
                            Usuario_Id = "109"
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            Apellidos = "Apellido 100",
                            Celular = "942024756",
                            Dni = "76368735",
                            Email = "paciente100@gmail.com",
                            FechaNacimiento = new DateTime(1904, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nombre 100",
                            Region = "Arequipa",
                            Sexo = 0,
                            Usuario_Id = "110"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
